/**
 * Runs anymd (Rust → WebAssembly) off the main thread so the page stays
 * responsive while a large PDF converts. The module is loaded at runtime from
 * the site's /wasm/ folder (generated by scripts/build-wasm.sh, not bundled).
 */

type Request =
  | { type: 'init'; base: string }
  | { type: 'convert'; id: number; name: string; bytes: ArrayBuffer };

interface AnymdModule {
  default: (options: { module_or_path: string }) => Promise<unknown>;
  convertDetailed: (bytes: Uint8Array, filename: string) => string;
  version: () => string;
}

let ready: Promise<AnymdModule> | null = null;

function load(base: string): Promise<AnymdModule> {
  ready ??= (async () => {
    const mod = (await import(/* @vite-ignore */ `${base}anymd_wasm.js`)) as AnymdModule;
    await mod.default({ module_or_path: `${base}anymd_wasm_bg.wasm` });
    return mod;
  })();
  return ready;
}

self.onmessage = async (event: MessageEvent<Request>) => {
  const message = event.data;
  if (message.type === 'init') {
    try {
      const started = performance.now();
      const mod = await load(message.base);
      self.postMessage({
        type: 'ready',
        version: mod.version(),
        loadMs: Math.round(performance.now() - started),
      });
    } catch (error) {
      self.postMessage({ type: 'unavailable', error: String(error) });
    }
    return;
  }
  const { id, name, bytes } = message;
  try {
    if (!ready) throw new Error('module not initialised');
    const mod = await ready;
    const started = performance.now();
    const result = JSON.parse(mod.convertDetailed(new Uint8Array(bytes), name));
    self.postMessage({ type: 'result', id, ms: performance.now() - started, ...result });
  } catch (error) {
    const text = error instanceof Error ? error.message : String(error);
    // A Rust panic traps the instance, so the page starts a fresh worker after any error.
    self.postMessage({ type: 'error', id, error: text });
  }
};
